docker: update build scripts and instructions to fix Docker emulator (#419)
fixes #417

diff --git a/script/fullbuild b/script/fullbuild
--- a/script/fullbuild
+++ b/script/fullbuild
@@ -22,6 +22,10 @@ readonly FIRMWARE_DIR="$BUILD_DIR/firmware"
 readonly FIRMWARE_FILENAME="firmware/trezor.bin"
 readonly FIRMWARE_PATH="$FIRMWARE_DIR/$FIRMWARE_FILENAME"
 
+readonly EMULATOR_DIR="$FIRMWARE_DIR"
+readonly EMULATOR_FILENAME="firmware/trezor-emulator.elf"
+readonly EMULATOR_PATH="$EMULATOR_DIR/firmware/trezor.elf"
+
 worktree_setup() {
     local path="$1"
     local commit="$2"
@@ -38,7 +42,21 @@ worktree_setup() {
 worktree_build() {
     local path="$1"
 
-    ( cd "$path" && pipenv install && pipenv run script/cibuild )
+    if [ -e "$path/Pipfile" ]; then
+        pushd $path
+        if ! pipenv install; then
+            # older tags can fail because they don't have protobuf in Pipfile
+            pipenv run pip install "protobuf==3.4.0"
+            pipenv install
+        fi
+        pipenv run script/cibuild
+        popd
+    else
+        # even older tags don't have Pipfile!
+        # use current one
+        pipenv install
+        ( cd "$path" && pipenv run script/cibuild )
+    fi
 }
 
 worktree_copy() {
@@ -67,28 +85,42 @@ main() {
     local firmware_commit="$2"
 
     script/bootstrap
-
-    worktree_setup "$BOOTLOADER_DIR" "$bootloader_commit"
-    worktree_build "$BOOTLOADER_DIR"
-
-    local bootloader_path="$(worktree_copy \
-        "$BOOTLOADER_DIR" \
-        "$BOOTLOADER_FILENAME" \
-        "bl*")"
-
     worktree_setup "$FIRMWARE_DIR" "$firmware_commit"
-    cp "$BOOTLOADER_PATH" "$FIRMWARE_DIR/$BOOTLOADER_FILENAME"
+
+    if [ "$EMULATOR" != 1 ]; then
+        worktree_setup "$BOOTLOADER_DIR" "$bootloader_commit"
+        worktree_build "$BOOTLOADER_DIR"
+
+        cp "$BOOTLOADER_PATH" "$FIRMWARE_DIR/$BOOTLOADER_FILENAME"
+    fi
+
     worktree_build "$FIRMWARE_DIR"
 
-    local firmware_path="$(worktree_copy \
-        "$FIRMWARE_DIR" \
-        "$FIRMWARE_FILENAME" \
-        "v*")"
+    if [ "$EMULATOR" = 1 ]; then
+        cp "$EMULATOR_PATH" "$EMULATOR_DIR/$EMULATOR_FILENAME"
+        local firmware_path="$(worktree_copy \
+            "$EMULATOR_DIR" \
+            "$EMULATOR_FILENAME" \
+            "v*")"
+        chmod +x "$firmware_path"
 
-    printf "\n\n"; $PYTHON script/fingerprint \
-        "$bootloader_path" \
-        --max-size 32768 \
-        --double
+    else
+
+        local firmware_path="$(worktree_copy \
+            "$FIRMWARE_DIR" \
+            "$FIRMWARE_FILENAME" \
+            "v*")"
+
+        local bootloader_path="$(worktree_copy \
+            "$BOOTLOADER_DIR" \
+            "$BOOTLOADER_FILENAME" \
+            "bl*")"
+
+        printf "\n\n"; $PYTHON script/fingerprint \
+            "$bootloader_path" \
+            --max-size 32768 \
+            --double
+    fi
 
     printf "\n\n"; $PYTHON script/fingerprint \
         "$firmware_path" \
