tools: update build_protobuf and pb2py to the refactored versions from python-trezor, with appropriate modifications for trezor-core
The end goal is to have these files identical, ideally coming from
trezor-common. This is most of the way there, only thing remaining
is handling of target paths.

diff --git a/tools/build_protobuf b/tools/build_protobuf
--- a/tools/build_protobuf
+++ b/tools/build_protobuf
@@ -1,34 +1,72 @@
 #!/bin/bash
-CURDIR=$(pwd)
-PB2DIR=$CURDIR/pb2
-OUTDIR=../src/trezor/messages
-INDEX=$OUTDIR/wire_types.py
+set -e
 
-set -x
+IS_CORE=""
 
-rm -f $OUTDIR/[A-Z]*.py
-mkdir -p $OUTDIR
-mkdir -p $PB2DIR
-touch $PB2DIR/__init__.py
+if [ "$1" == "--core" ]; then
+    shift
+    IS_CORE=yes
+elif [ "$1" == "--no-core" ]; then
+    shift
+elif echo $PWD | grep -q "trezor-core"; then
+    IS_CORE=yes
+fi
 
-rm -f $INDEX
-echo '# Automatically generated by pb2py' >> $INDEX
-echo 'from micropython import const' >> $INDEX
-echo '' >> $INDEX
+if [ -n "$1" ]; then
+    OUTDIR=`readlink -f "$1"`
+fi
 
-for i in types messages ; do
-    # Compile .proto files to python2 modules using google protobuf library
-    cd $CURDIR/../vendor/trezor-common/protob
-    protoc --python_out=$PB2DIR -I/usr/include -I. $i.proto
+cd "$(dirname "$0")"
+
+# set up paths
+INDEX="__init__.py"
+GENPATH="${OUTDIR:-../src/trezor/messages}"
+PROTO_PATH="../../trezor-common/protob"
+PROTO_FILES="types messages"
+
+# set up temporary directory & cleanup
+TMPDIR=$(mktemp -d)
+function cleanup {
+    rm -r $TMPDIR
+}
+trap cleanup EXIT
+
+# set up pb2 outdir
+PB2_OUT="$TMPDIR/pb2"
+mkdir -p "$PB2_OUT"
+
+# compile .proto files to python2 modules using google protobuf library
+for file in $PROTO_FILES; do
+    protoc --python_out="$PB2_OUT" -I/usr/include -I"$PROTO_PATH" "$PROTO_PATH/$file.proto"
 done
 
-# hack to make output python 3 compatible
-sed -i 's/^import types_pb2/from . import types_pb2/g' $CURDIR/pb2/messages_pb2.py
 
-for i in types messages ; do
-    # Convert google protobuf library to trezor's internal format
-    cd $CURDIR
-    ./pb2py -m -p $CURDIR -i $INDEX $i $OUTDIR
+if [ -n "$IS_CORE" ]; then
+    # generate for micropython
+    PB2PY_OPTS="-m"
+else
+    # create index (__init__.py)
+    echo "# Automatically generated by pb2py" > $TMPDIR/$INDEX
+    echo >> $TMPDIR/$INDEX
+    PB2PY_OPTS="-l $TMPDIR/$INDEX"
+fi
+
+# convert google protobuf library to trezor's internal format
+for file in $PROTO_FILES; do
+    ./pb2py $PB2PY_OPTS -P "trezorlib.protobuf" -p "$PB2_OUT" "$file" "$TMPDIR"
 done
 
-rm -rf $PB2DIR
+if [ -n "$IS_CORE" ]; then
+    cp "$TMPDIR/MessageType.py" "$TMPDIR/wire_types.py"
+fi
+
+# ensure $GENPATH exists and is empty of messages
+mkdir -p "$GENPATH"
+# only remove messages - there could possibly be other files not starting with capital letter
+rm -f "$GENPATH"/[A-Z]*.py
+
+# move generated files to the destination
+# (this assumes $INDEX is *.py, otherwise we'd have to add $INDEX separately)
+mv "$TMPDIR"/*.py "$GENPATH"
+
+# the exit trap handles removing the tmp directory
